### ISSUE TITLE
on Windows Chrome, the page has the bottom scroll bar visible (see screenshots)

### ISSUE THREAD

**Issue by yelsre** [ollayka/house-of-plants#28]

**Comment by yelsre** [comment]
Before:

![image](https://user-images.githubusercontent.com/51226492/115145864-2007a100-a054-11eb-900a-e6c731c6d2c1.png)
========================================================================

After:

![image](https://user-images.githubusercontent.com/51226492/115145888-49283180-a054-11eb-9cf6-2c4b3ef0d820.png)

**Comment by heyiamola** [comment]
nice catch, thanks for the fix!
